# /// script
# requires-python = ">=3.11"
# ///
"""Turn the CONFIG_LV_* lines of an ESP-IDF sdkconfig into a C header the
desktop simulator feeds to LVGL, so the host build uses exactly the LVGL
configuration the device was built with (fonts, colour depth, renderer).

  uv run tools/lvconf.py --sdkconfig firmware/sdkconfig.ws169 --out sim/lv_kconfig.h
  uv run tools/lvconf.py --sdkconfig firmware/sdkconfig.ws169 --check sim/lv_kconfig.h

--check exits 1 when the committed header is out of date. The simulator's
CMake runs that check whenever the sdkconfig exists locally.
"""
from __future__ import annotations

import argparse
import re
import sys

LINE = re.compile(r"^(CONFIG_LV_[A-Z0-9_]+)=(.*)$")


def convert(sdkconfig_text: str, source: str) -> str:
    out = [
        "// GENERATED by tools/lvconf.py from " + source + " - do not edit.",
        "// Regenerate with `make sim-lvconf` after the firmware's LVGL config changes.",
        "#pragma once",
    ]
    for raw in sdkconfig_text.splitlines():
        m = LINE.match(raw.strip())
        if not m:
            continue
        name, value = m.groups()
        if value == "y":
            value = "1"
        elif value == "n":
            continue
        out.append(f"#define {name} {value}")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sdkconfig", required=True)
    ap.add_argument("--out", help="write the header here")
    ap.add_argument("--check", help="compare against this header instead of writing")
    args = ap.parse_args()
    with open(args.sdkconfig) as f:
        header = convert(f.read(), args.sdkconfig.replace("\\", "/").split("/")[-1])
    if args.check:
        try:
            current = open(args.check).read()
        except FileNotFoundError:
            current = ""
        if current != header:
            print(f"{args.check} is out of date with {args.sdkconfig}; run `make sim-lvconf`", file=sys.stderr)
            return 1
        return 0
    if not args.out:
        sys.exit("pass --out or --check")
    with open(args.out, "w") as f:
        f.write(header)
    print(f"{args.out}: {header.count(chr(10)) - 3} options from {args.sdkconfig}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
